services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - cim_cim_identity_network

networks: 
  cim_cim_identity_network: 
    external: true
